<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsTestProject>true</IsTestProject>
		<Platforms>AnyCPU;x64</Platforms>
		<RunSettingsFilePath>$(MSBuildProjectDirectory)/../.runsettings</RunSettingsFilePath>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Moq" Version="4.20.72" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.5.1" />
		<PackageReference Include="FluentAssertions" Version="8.9.0" />
		<PackageReference Include="xunit.v3" Version="3.2.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="../../../../FixPointCS/Examples/FixMath/FixMath.csproj" />
		<ProjectReference Include="..\CSharpCraft\CSharpCraft.csproj" />
		<ProjectReference Include="../../../../FNA/FNA.Core.csproj" />
	    <ProjectReference Include="../../PSharp8/PSharp8/PSharp8.csproj" />
	</ItemGroup>

	
	<!-- Copy native FNA libraries to the output directory so they can be found at runtime -->
	<Import Project="../FNALibs.props" />
	<ItemGroup>
		<None Include="TestAssets/**" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>
	
</Project>
