<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Platforms>AnyCPU;x64</Platforms>
		<PublishSingleFile>true</PublishSingleFile>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<Target Name="CreateSeedsFolder" BeforeTargets="Build">
		<MakeDir Directories="$(OutputPath)Seeds" />
	</Target>

	<ItemGroup>
	  <PackageReference Include="DeepCloner" Version="0.10.4" />
	  <PackageReference Include="Google.Protobuf" Version="3.30.2" />
	  <PackageReference Include="Grpc.Net.Client" Version="2.71.0" />
	  <PackageReference Include="Grpc.Tools" Version="2.72.0">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	  <PackageReference Include="NativeFileDialogs.Net" Version="1.2.1" />
	  <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
	  <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include="Content\**\*">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>

	<ItemGroup>
		<None Include="../FNAlibs/**" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Protos\" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="../../../../FNA/FNA.Core.csproj" />
	  <ProjectReference Include="../../PSharp8/PSharp8/PSharp8.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Protobuf Include="..\RaceServer.Deprecated\Protos\account.proto">
	    <Link>Protos\account.proto</Link>
	  </Protobuf>
	  <Protobuf Include="..\RaceServer.Deprecated\Protos\gameservice.proto">
	    <Link>Protos\gameservice.proto</Link>
	  </Protobuf>
	</ItemGroup>

</Project>
