using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CSharpCraft
{
    public class KeyNames
    {
        public static Dictionary<string, string> keyNames = new()
        {
            { "LeftButton", "l click" },
            { "RightButton", "r click" },
            { "MiddleButton", "m click" },
            { "XButton1", "extra 1" },
            { "XButton2", "extra 2" },
            { "ScrollWheelValue", "scroll" },
            { "None", "none" },
            { "Back", "back" },
            { "Tab", "tab" },
            { "Enter", "enter" },
            { "CapsLock", "caps" },
            { "Escape", "esc" },
            { "Space", "space" },
            { "PageUp", "pgup" },
            { "PageDown", "pgdown" },
            { "End", "end" },
            { "Home", "home" },
            { "Left", "left" },
            { "Up", "up" },
            { "Right", "right" },
            { "Down", "down" },
            { "Select", "select" },
            { "Print", "print" },
            { "Execute", "execute" },
            { "PrintScreen", "prt sc" },
            { "Insert", "insert" },
            { "Delete", "delete" },
            { "Help", "help" },
            { "D0", "0" },
            { "D1", "1" },
            { "D2", "2" },
            { "D3", "3" },
            { "D4", "4" },
            { "D5", "5" },
            { "D6", "6" },
            { "D7", "7" },
            { "D8", "8" },
            { "D9", "9" },
            { "A", "a" },
            { "B", "b" },
            { "C", "c" },
            { "D", "d" },
            { "E", "e" },
            { "F", "f" },
            { "G", "g" },
            { "H", "h" },
            { "I", "i" },
            { "J", "j" },
            { "K", "k" },
            { "L", "l" },
            { "M", "m" },
            { "N", "n" },
            { "O", "o" },
            { "P", "p" },
            { "Q", "q" },
            { "R", "r" },
            { "S", "s" },
            { "T", "t" },
            { "U", "u" },
            { "V", "v" },
            { "W", "w" },
            { "X", "x" },
            { "Y", "y" },
            { "Z", "z" },
            { "LeftWindows", "rwin" },
            { "RightWindows", "rwin" },
            { "Apps", "apps" },
            { "Sleep", "sleep" },
            { "NumPad0", "num0" },
            { "NumPad1", "num1" },
            { "NumPad2", "num2" },
            { "NumPad3", "num3" },
            { "NumPad4", "num4" },
            { "NumPad5", "num5" },
            { "NumPad6", "num6" },
            { "NumPad7", "num7" },
            { "NumPad8", "num8" },
            { "NumPad9", "num9" },
            { "Multiply", "mult" },
            { "Add", "add" },
            { "Separator", "sepratr" },
            { "Subtract", "sub" },
            { "Decimal", "decimal" },
            { "Divide", "div" },
            { "F1", "f1" },
            { "F2", "f2" },
            { "F3", "f3" },
            { "F4", "f4" },
            { "F5", "f5" },
            { "F6", "f6" },
            { "F7", "f7" },
            { "F8", "f8" },
            { "F9", "f9" },
            { "F10", "f10" },
            { "F11", "f11" },
            { "F12", "f12" },
            { "F13", "f13" },
            { "F14", "f14" },
            { "F15", "f15" },
            { "F16", "f16" },
            { "F17", "f17" },
            { "F18", "f18" },
            { "F19", "f19" },
            { "F20", "f20" },
            { "F21", "f21" },
            { "F22", "f22" },
            { "F23", "f23" },
            { "F24", "f24" },
            { "NumLock", "numlock" },
            { "Scroll", "scrlock"},
            { "LeftShift", "lshift" },
            { "RightShift", "rshift" },
            { "LeftControl", "lctrl" },
            { "RightControl", "rctrl" },
            { "LeftAlt", "lalt" },
            { "RightAlt", "ralt" },
            { "BrowserBack", "br back" },
            { "BrowserForward", "br for"},
            { "BrowserRefresh", "br ref"},
            { "BrowserStop", "br stop" },
            { "BrowserSearch", "br ser" },
            { "BrowserFavorites", "br fav" },
            { "BrowserHome", "br home" },
            { "VolumeMute", "mute" },
            { "VolumeDown", "vol -" },
            { "VolumeUp", "vol +" },
            { "MediaNextTrack", "next" },
            { "MediaPreviousTrack", "prev" },
            { "MediaStop", "stop" },
            { "MediaPlayPause", ">/||" },
            { "LaunchMail", "mail" },
            { "SelectMedia", "slctmed" },
            { "LaunchApplication1", "launch 1" },
            { "LaunchApplication2", "launch 2" },
            { "OemSemicolon", ";" },
            { "OemPlus", "+" },
            { "OemComma", "," },
            { "OemMinus", "-" },
            { "OemPeriod", "." },
            { "OemQuestion", "?" },
            { "OemTilde", "~" },
            { "OemOpenBrackets", "[" },
            { "OemPipe", "|" },
            { "OemCloseBrackets", "]" },
            { "OemQuotes", "'" },
            { "Oem8", "8" },
            { "OemBackslash", "\\" },
            { "ProcessKey", "process" },
            { "Attn", "attn" },
            { "Crsel", "crsel" },
            { "Exsel", "exsel" },
            { "EraseEof", "erase" },
            { "Play", "play" },
            { "Zoom", "zoom" },
            { "Pa1", "pa1" },
            { "OemClear", "clear" },
            { "ChatPadGreen", "chat gr" },
            { "ChatPadOrange", "chat or" },
            { "Pause", "pause" },
            { "ImeConvert", "convert" },
            { "ImeNoConvert", "nocnvert" },
            { "Kana", "kana" },
            { "Kanji", "kanji" },
            { "OemAuto", "auto" },
            { "OemCopy", "copy" },
            { "OemEnlW", "enlw" }
        };

    }
}
