using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.Xna.Framework.Input;

namespace CSharpCraft
{
    public class KeysToString
    {
        public static Dictionary<Keys, string> keysToString = new()
        {
            { Keys.None, "None" },
            { Keys.Back, "Back" },
            { Keys.Tab, "Tab" },
            { Keys.Enter, "Enter" },
            { Keys.CapsLock, "CapsLock" },
            { Keys.Escape, "Escape" },
            { Keys.Space, "Space" },
            { Keys.PageUp, "PageUp" },
            { Keys.PageDown, "PageDown" },
            { Keys.End, "End" },
            { Keys.Home, "Home" },
            { Keys.Left, "Left" },
            { Keys.Up, "Up" },
            { Keys.Right, "Right" },
            { Keys.Down, "Down" },
            { Keys.Select, "Select" },
            { Keys.Print, "Print" },
            { Keys.Execute, "Execute" },
            { Keys.PrintScreen, "PrintScreen" },
            { Keys.Insert, "Insert" },
            { Keys.Delete, "Delete" },
            { Keys.Help, "Help" },
            { Keys.D0, "D0" },
            { Keys.D1, "D1" },
            { Keys.D2, "D2" },
            { Keys.D3, "D3" },
            { Keys.D4, "D4" },
            { Keys.D5, "D5" },
            { Keys.D6, "D6" },
            { Keys.D7, "D7" },
            { Keys.D8, "D8" },
            { Keys.D9, "D9" },
            { Keys.A, "A" },
            { Keys.B, "B" },
            { Keys.C, "C" },
            { Keys.D, "D" },
            { Keys.E, "E" },
            { Keys.F, "F" },
            { Keys.G, "G" },
            { Keys.H, "H" },
            { Keys.I, "I" },
            { Keys.J, "J" },
            { Keys.K, "K" },
            { Keys.L, "L" },
            { Keys.M, "M" },
            { Keys.N, "N" },
            { Keys.O, "O" },
            { Keys.P, "P" },
            { Keys.Q, "Q" },
            { Keys.R, "R" },
            { Keys.S, "S" },
            { Keys.T, "T" },
            { Keys.U, "U" },
            { Keys.V, "V" },
            { Keys.W, "W" },
            { Keys.X, "X" },
            { Keys.Y, "Y" },
            { Keys.Z, "Z" },
            { Keys.LeftWindows, "LeftWindows" },
            { Keys.RightWindows, "RightWindows" },
            { Keys.Apps, "Apps" },
            { Keys.Sleep, "Sleep" },
            { Keys.NumPad0, "NumPad0" },
            { Keys.NumPad1, "NumPad1" },
            { Keys.NumPad2, "NumPad2" },
            { Keys.NumPad3, "NumPad3" },
            { Keys.NumPad4, "NumPad4" },
            { Keys.NumPad5, "NumPad5" },
            { Keys.NumPad6, "NumPad6" },
            { Keys.NumPad7, "NumPad7" },
            { Keys.NumPad8, "NumPad8" },
            { Keys.NumPad9, "NumPad9" },
            { Keys.Multiply, "Multiply" },
            { Keys.Add, "Add" },
            { Keys.Separator, "Separator" },
            { Keys.Subtract, "Subtract" },
            { Keys.Decimal, "Decimal" },
            { Keys.Divide, "Divide" },
            { Keys.F1, "F1" },
            { Keys.F2, "F2" },
            { Keys.F3, "F3" },
            { Keys.F4, "F4" },
            { Keys.F5, "F5" },
            { Keys.F6, "F6" },
            { Keys.F7, "F7" },
            { Keys.F8, "F8" },
            { Keys.F9, "F9" },
            { Keys.F10, "F10" },
            { Keys.F11, "F11" },
            { Keys.F12, "F12" },
            { Keys.F13, "F13" },
            { Keys.F14, "F14" },
            { Keys.F15, "F15" },
            { Keys.F16, "F16" },
            { Keys.F17, "F17" },
            { Keys.F18, "F18" },
            { Keys.F19, "F19" },
            { Keys.F20, "F20" },
            { Keys.F21, "F21" },
            { Keys.F22, "F22" },
            { Keys.F23, "F23" },
            { Keys.F24, "F24" },
            { Keys.NumLock, "NumLock" },
            { Keys.Scroll, "Scroll"},
            { Keys.LeftShift, "LeftShift" },
            { Keys.RightShift, "RightShift" },
            { Keys.LeftControl, "LeftControl" },
            { Keys.RightControl, "RightControl" },
            { Keys.LeftAlt, "LeftAlt" },
            { Keys.RightAlt, "RightAlt" },
            { Keys.BrowserBack, "BrowserBack" },
            { Keys.BrowserForward, "BrowserForward"},
            { Keys.BrowserRefresh, "BrowserRefresh"},
            { Keys.BrowserStop, "BrowserStop" },
            { Keys.BrowserSearch, "BrowserSearch" },
            { Keys.BrowserFavorites, "BrowserFavorites" },
            { Keys.BrowserHome, "BrowserHome" },
            { Keys.VolumeMute, "VolumeMute" },
            { Keys.VolumeDown, "VolumeDown" },
            { Keys.VolumeUp, "VolumeUp" },
            { Keys.MediaNextTrack, "MediaNextTrack" },
            { Keys.MediaPreviousTrack, "MediaPreviousTrack" },
            { Keys.MediaStop, "MediaStop" },
            { Keys.MediaPlayPause, "MediaPlayPause" },
            { Keys.LaunchMail, "LaunchMail" },
            { Keys.SelectMedia, "SelectMedia" },
            { Keys.LaunchApplication1, "LaunchApplication1" },
            { Keys.LaunchApplication2, "LaunchApplication2" },
            { Keys.OemSemicolon, "OemSemicolon" },
            { Keys.OemPlus, "OemPlus" },
            { Keys.OemComma, "OemComma" },
            { Keys.OemMinus, "OemMinus" },
            { Keys.OemPeriod, "OemPeriod" },
            { Keys.OemQuestion, "OemQuestion" },
            { Keys.OemTilde, "OemTilde" },
            { Keys.OemOpenBrackets, "OemOpenBrackets" },
            { Keys.OemPipe, "OemPipe" },
            { Keys.OemCloseBrackets, "OemCloseBrackets" },
            { Keys.OemQuotes, "OemQuotes" },
            { Keys.Oem8, "Oem8" },
            { Keys.OemBackslash, "OemBackslash" },
            { Keys.ProcessKey, "ProcessKey" },
            { Keys.Attn, "Attn" },
            { Keys.Crsel, "Crsel" },
            { Keys.Exsel, "Exsel" },
            { Keys.EraseEof, "EraseEof" },
            { Keys.Play, "Play" },
            { Keys.Zoom, "Zoom" },
            { Keys.Pa1, "Pa1" },
            { Keys.OemClear, "OemClear" },
            { Keys.ChatPadGreen, "ChatPadGreen" },
            { Keys.ChatPadOrange, "ChatPadOrange" },
            { Keys.Pause, "Pause" },
            { Keys.ImeConvert, "ImeConvert" },
            { Keys.ImeNoConvert, "ImeNoConvert" },
            { Keys.Kana, "Kana" },
            { Keys.Kanji, "Kanji" },
            { Keys.OemAuto, "OemAuto" },
            { Keys.OemCopy, "OemCopy" },
            { Keys.OemEnlW, "OemEnlW" }
        };

    }
}
